---
apiVersion: v1
kind: Service
metadata:
  namespace: svc
  name: svc-hmt-cargo
  annotations:
    beta.cloud.google.com/backend-config: 
      '{"ports": {"80":"backend-config-hmt-cargo-svc"}}'
spec:
  selector:
    app: svc-hmt-cargo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: svc
  name: svc-hmt-cargo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: svc-hmt-cargo
  template:
    metadata:
      labels:
        app: svc-hmt-cargo
    spec:
      containers: 
      - name: svc-hmt-cargo 
        image: gcr.io/bwing-230309/hmt/cargo/prd/svc:9922af8
        imagePullPolicy: Always
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: TZ
          value: Asia/Tokyo
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json 
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: 100Mi
            cpu: 10m
          limits:
            memory: 150Mi
            cpu: 30m
      volumes:
      - name: google-cloud-key
        secret:
          secretName: cargo-iam-key
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  namespace: svc
  name: svc-hmt-cargo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: svc-hmt-cargo
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu 
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: svc
  name: ingress-hmt-cargo-svc
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.global-static-ip-name: svc-hmt-cargo-static-ip
    networking.gke.io/managed-certificates: certificate-hmt-cargo-svc
spec:
  defaultBackend:
    service:
      name: svc-hmt-cargo
      port:
        number: 80
