apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
  namespace: kube-system
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    #server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: hiramatsu@svc.co.jp
    privateKeySecretRef:
      name: letsencrypt-issuer
    solvers:
    - selector: {}
      dns01:
        clouddns:
          project: bwing-230309
          serviceAccountSecretRef:
            name: k8s-dns-secret
            key: key.json
