---
apiVersion: v1
kind: Service
metadata:
  namespace: svc
  name: svc-hmt-gyroscope
  annotations:
    beta.cloud.google.com/backend-config: 
      '{"ports": {"80":"backend-config-hmt-gyroscope-svc"}}'
spec:
  selector:
    app: svc-hmt-gyroscope
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: svc
  name: svc-hmt-gyroscope
spec:
  replicas: 3
  selector:
    matchLabels:
      app: svc-hmt-gyroscope
  serviceName: svc-hmt-gyroscope
  template:
    metadata:
      labels:
        app: svc-hmt-gyroscope
    spec:
      containers: 
      - name: svc-hmt-gyroscope 
        image: gcr.io/bwing-230309/hmt/gyroscope/prd/svc:0d661a1
        imagePullPolicy: Always
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        - name: svc-hmt-gyroscope-pvc
          mountPath: /mnt/gyroscope/events
        env:
        - name: TZ
          value: Asia/Tokyo
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json 
        - name: LOCAL_OR_REMOTE
          value: remote
        - name: GCP_PROJECT_ID
          value: bwing-230309
        - name: SERVER_CODE
          value: svc
        - name: APPLI_NAME
          value: gyroscope
        - name: SERIES
          value: v2
        - name: ENV
          value: prd
        - name: GCS_BUCKET_NAME
          value: gyroscope
        - name: GCS_BUCKET_PATH
          value: events
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: 100Mi
            cpu: 10m
          limits:
            memory: 200Mi
            cpu: 30m
      volumes:
      - name: google-cloud-key
        secret:
          secretName: gyroscope-iam-key
      - name: svc-hmt-gyroscope-pvc
        persistentVolumeClaim:
          claimName: svc-hmt-gyroscope-pvc
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  namespace: svc
  name: svc-hmt-gyroscope
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: svc-hmt-gyroscope
  minReplicas: 4
  maxReplicas: 18
  metrics:
  - type: Resource
    resource:
      name: cpu 
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 60
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: svc
  name: ingress-hmt-gyroscope-svc
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.global-static-ip-name: svc-hmt-gyroscope-static-ip
    networking.gke.io/managed-certificates: certificate-hmt-svc
spec:
  defaultBackend:
    service:
      name: svc-hmt-gyroscope
      port:
        number: 80
